openapi: 3.0.0
info:
  title: Music Playlist API
  version: "1.0.0"
  description: API to add a new song to an existing playlist
servers:
  - url: http://localhost:8080

paths:
  /users/{userId}/playlists/{playlistId}/songs:
    post:
      summary: Add a new song to an existing playlist
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
        - name: playlistId
          in: path
          required: true
          description: The ID of the playlist to which the song will be added
          schema:
            type: integer
      requestBody:
        description: Song details to add to the playlist
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewSong'
      responses:
        '201':
          description: Song added successfully
        '400':
          description: Bad request
          content:
            application/json:
              example:
                error: "Invalid request payload"
        '404':
          description: User or playlist not found
          content:
            application/json:
              example:
                error: "User or playlist not found"
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: "Internal Server Error"
      security:
        - apiKey: []

components:
  schemas:
    NewSong:
      type: object
      properties:
        title:
          type: string
        artist:
          type: string
