
openapi: 3.0.0
info:
  title: Music Playlist API
  version: "1.0.0"
  description: API to create a new playlist for a user and to display all the playlists for a particular user
servers:
  - url: http://localhost:8080

paths:
  /users/{userId}/playlists:
    get:
      description: Get a list of user playlists
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user whose playlists to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                playlists:
                  - id: 1
                    name: "My Favorites"
                    tracks: 20
                  - id: 2
                    name: "Workout Jams"
                    tracks: 15
        '404':
          description: User not found
          content:
            application/json:
              example:
                error: "User not found"
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: "Internal Server Error"
      security:
        - apiKey: []
    post:
      summary: Create a new playlist
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user for whom the playlist is created
          schema:
            type: string
      requestBody:
        description: Playlist details for creation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPlaylist'
      responses:
        '201':
          description: Playlist created successfully
          content:
            application/json:
              example:
                id: 123
                name: "My New Playlist"
                description: "A description of the new playlist"
                tracks:
                  - title: "Song 1"
                    artist: "Artist 1"
                  - title: "Song 2"
                    artist: "Artist 2"
        '400':
          description: Bad request
          content:
            application/json:
              example:
                error: "Invalid request payload"
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: "Internal Server Error"
      security:
        - apiKey: []

components:
  schemas:
    UserPlaylists:
      type: object
      properties:
        playlists:
          type: array
          items:
            $ref: '#/components/schemas/Playlist'
    Playlist:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        tracks:
          type: integer
    NewPlaylist:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        tracks:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              artist:
                type: string